version: '3.8'

services:
  app:
    image: shorturl
    container_name: shorturl_app
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - shorturl_network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/shorturl
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
    ports:
      - "8080:8080"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: shorturl
    ports:
      - "3307:3306"
    networks:
      - shorturl_network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5
      start_period: 20s

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6378:6379"
    networks:
      - shorturl_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      retries: 5
      start_period: 20s

networks:
  shorturl_network:
    name: shorturl_network
    driver: bridge